---
title: "Assignment 2"
author: "Kathryn Agnas"
date: "3/1/2021"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include = F}
rm(list=ls())
gc() 
```

```{r}
library(readxl) 
library(tidyverse)
library(ggthemes)
```

```{r}
Demo <- read_excel("~/Desktop/LIFE.xlsx")
#View(Demo)
```

```{r}
Demo$Region[Demo$Region==1] <- "More Developed Region"
Demo$Region[Demo$Region==2] <- "Less Developed Region"
Demo$Region[Demo$Region==3] <- "North America"
Demo$Region[Demo$Region==4] <-"United States of America"
 
Demo$Region <- factor(Demo$Region, levels=c(""More Developed Region","North America","Less Developed Region", "More Developed Region"))

Demo$Year[Demo$Year==1] <- "1950-1955"
Demo$Year[Demo$Year==2] <- "1955-1960"
Demo$Year[Demo$Year==3] <- "1960-1965"
Demo$Year[Demo$Year==4] <- "1965-1970"
Demo$Year[Demo$Year==5] <- "1970-1975"
Demo$Year[Demo$Year==6] <- "1975-1980"
Demo$Year[Demo$Year==7] <- "1980-1985"
Demo$Year[Demo$Year==8] <- "1985-1990"
Demo$Year[Demo$Year==9] <- "1990-1995"
Demo$Year[Demo$Year==10] <- "1995-2000"
Demo$Year[Demo$Year==11] <- "2000-2005"
Demo$Year[Demo$Year==12] <- "2005-2010"
Demo$Year[Demo$Year==13] <- "2010-2015"
Demo$Year[Demo$Year==14] <- "2015-2020"

Demo$Year <- factor(Demo$Year, levels=c("1950-1955", "1955-1960", "1960-1965","1965-1970","1970-1975","1975-1980","1980-1985","1985-1990","1990-1995","1995-2000","2000-2005","2005-2010","2010-2015","2015-2020"))
```


```{r}
Demo %>%
  ggplot(aes(x=Year,y=lifeexp)) + geom_line(aes(colour=Region,group=Region)) + theme_classic() + theme(plot.title=element_text(hjust=0.5)) + theme(plot.caption=element_text(hjust=0)) + labs(title="Trends for Life Expectancy at Birth of the U.S. Population", x="Year",y="Life Expectancy (years)",caption="Source: United Nations. World Population Prospect 2019. https://population.un.org/wpp/DataQuery/")  
```

```{r}
Demo %>%
  ggplot(aes(x=Year,y=cdr)) + geom_line(aes(colour=Region,group=Region)) + theme_classic() + theme(plot.title=element_text(hjust=0.5)) + theme(plot.caption=element_text(hjust=0)) + labs(title="Trends for Crude Death Rate in the U.S. Population", x="Year",y="Crude Death Rate (deaths per 1,000 population)", caption="Source: United Nations. World Population Prospect 2019. https://population.un.org/wpp/DataQuery/")  
```

```{r}
Demo %>%
  ggplot(aes(x=Year,y=imr)) + geom_line(aes(colour=Region,group=Region)) + theme_classic() + theme(plot.title=element_text(hjust=0.5)) + theme(plot.caption=element_text(hjust=0)) + labs(title="Trends for Infant Mortality Rate in the U.S. Population", x="Year",y="Infant Mortality Rate (infant deaths per 1,000 live births)", caption="Source: United Nations. World Population Prospect 2019. https://population.un.org/wpp/DataQuery/")  
```